# -*- coding: utf-8 -*-
"""Sentiment Dasboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g2LmEQ5IX8dEqeGrJrCOju7dXpEy023W
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from keras.models import load_model
import pickle
from utils import *  # fungsi bantu kamu simpan di utils.py

model = load_model("model/lstm_model.h5")
with open("model/tokenizer.pickle", "rb") as f:
    tokenizer = pickle.load(f)

st.sidebar.title("Menu Navigasi")
game_choice = st.sidebar.selectbox("Pilih Game", ["Genshin Impact", "Wuthering Waves"])
section = st.sidebar.radio("Pilih Section", ["Section 1: Analisa", "Section 2: Word Cloud", "Section 3: Uji Coba Model"])

if game_choice == "Genshin Impact":
    df = pd.read_csv("data/genshin_sentiment.csv")
else:
    df = pd.read_csv("data/wuthering_sentiment.csv")

if section.startswith("Section 1"):
    show_game_description(game_choice)
    show_sentiment_charts(df, game_choice)

elif section.startswith("Section 2"):
    show_wordclouds(df)

elif section.startswith("Section 3"):
    user_input = st.text_input("Masukkan kalimat komentar:")
    if user_input:
        analyze_user_input(user_input, model, tokenizer)