# -*- coding: utf-8 -*-
"""Sentiment Dasboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g2LmEQ5IX8dEqeGrJrCOju7dXpEy023W
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import tokenizer_from_json
import json

from utils import show_game_description, show_sentiment_charts, show_wordclouds, analyze_user_input

model = load_model("Model/sentiment_model.keras")
with open("Model/tokenizer_lstm.json") as f:
    tokenizer_json = json.load(f)
tokenizer = tokenizer_from_json(tokenizer_json)

st.sidebar.title("📊 Dashboard Sentimen Komentar")
game_choice = st.sidebar.selectbox("🎮 Pilih Game", ["Genshin Impact", "Wuthering Waves"])
section = st.sidebar.radio("📌 Pilih Section", ["Section 1: Analisa", "Section 2: Word Cloud", "Section 3: Uji Coba Model"])

if game_choice == "Genshin Impact":
    df = pd.read_csv("Data/Sentiment_Genshin.csv")
else:
    df = pd.read_csv("Data/Sentiment_Wuthering.csv")

st.title("Analisis Sentimen Komentar Game 🎮")
st.markdown("""
**LSTM (Long Short-Term Memory)** adalah jenis jaringan saraf yang efektif dalam memahami konteks kalimat, cocok untuk analisis sentimen.

**NLTK (Natural Language Toolkit)** membantu dalam preprocessing teks, seperti tokenisasi dan penghapusan kata yang tidak penting (stopwords).

Kombinasi LSTM dan NLTK memungkinkan analisis sentimen yang akurat dan efisien.
""")

if section.startswith("Section 1"):
    show_game_description(game_choice)
    show_sentiment_charts(df, game_choice)

elif section.startswith("Section 2"):
    show_wordclouds(df)

elif section.startswith("Section 3"):
    st.subheader("🧪 Uji Coba Model Sentimen")
    user_input = st.text_input("Masukkan kalimat komentar:")
    if user_input:
        analyze_user_input(user_input, model, tokenizer)
