# -*- coding: utf-8 -*-
"""Google Play Scraper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CWlL6abh2WAM-9HmEDUFyXXdcURpmsCK

## Install Google Play Scraper
"""

!pip install google-play-scraper

"""## Library"""

import pandas as pd
from google_play_scraper import app, reviews

app_id = "com.kurogame.wutheringwaves.global"
num_reviews = 5000

"""Baris kode ini menetapkan dua variabel yang akan digunakan untuk scraping data dari Google Play Store menggunakan `google_play_scraper`.

Penjelasan:
1. `app_id = "com.kurogame.wutheringwaves.global"`
- app_id berisi package name dari aplikasi di Google Play Store.

2. `num_reviews = 5000`
- Menentukan jumlah ulasan (reviews) yang ingin diambil dari Google Play
"""

app_info = app(app_id)

"""berfungsi untuk mengambil informasi lengkap tentang aplikasi dari Google Play Store berdasarkan app_id.

"""

result, continuation_token = reviews(
    app_id,
    lang='en',
    country='us',
    count=num_reviews,
)

"""adalah inti dari proses mengambil ulasan pengguna (`reviews`) dari aplikasi di Google Play Store.

Penjelasan:
1. `reviews()` dipanggil dari `google_play_scraper.reviews`, fungsi ini digunakan untuk mengambil ulasan aplikasi secara langsung dari Google Play.
- `app_id`
Id unik aplikasi.
- `lang='en'`
Mengatur bahasa ulasan ke dalam bahasa inggris.
- `country='us'`
Mengatur asal negara ulasan.
- `count=num_reviews`
Jumlah review yang ingin diambil
"""

data=[]
for review in result:
    data.append({'Review': review['content'],
                 })

"""Berfungsi untuk menyusun ulang data dari hasil review menjadi list of dictionaries yang hanya menyimpan isi ulasan (review content) saja.

Penjelasan:
1. `data = []`
Membuat list kosong untuk menampung data ulasan yang sudah diformat.
2. `for review in result:`
melakukan iterasi (looping) ke setiap item `review` dalam list hasil `result` dari fungsi `reviews()`.
3. `data.append({'Review': review['content']})`
Menambahkan dictionary ke list `data`, hanya dengan satu key: '`Review`', dan nilainya adalah isi teks ulasan dair pengguna (`Review['content']`).
"""

df = pd.DataFrame(data)
df.to_csv('Wuthering_Reviews.csv', index=False, encoding='utf-8')

"""1. `df = pd.DataFrame(data)`
- Mengubah list of dictionaries (`data`) menjadi DataFrame (tabel) dengan `pandas`.
- Karena setiap item dalam `data` punya satu key '`Review`', maka hasil DataFrame akan punya satu kolom saja: `Review`.
2. `df.to_csv('Wuthering_Reviews.csv', index=False, encoding='utf-8')`
- Menyimpan DataFrame kedalam CSV.
- `index=False` berarti tidak menyertakan indeks baris kedalam file CSV.
- `encoding = 'utf-8'` menastikan file bisa dibuka tanpa masalah karakter (terutama jika mengandung emoji atau karakter)
"""

df = pd.read_csv('Wuthering_Reviews.csv')
df.head(10)

"""1. `df = pd.read_csv('Wuthering_Reviews.csv')`
- Membaca file CSV
2. `df.head(10)`
- Menampilkan 10 baris pertama dari DataFrame

"""

df.info()

"""Digunakan untuk menampilkan ringkasan struktur DataFrame."""

from google.colab import files
files.download('Wuthering_Reviews.csv')

"""Untuk mengunduk file CSV"""